version: '3.1'

services:
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - development

volumes:
    db-redis:
        driver: local
networks:
    development:
        driver: bridge
