version: '3.1'

services:
  db-meilisearch:
    image: 'getmeili/meilisearch:latest'
    ports:
      - '7700:7700'
    environment:
      MEILI_NO_ANALYTICS: '${MEILISEARCH_NO_ANALYTICS:-false}'
    volumes:
      - 'db-meilisearch:/meili_data'
    healthcheck:
      test:
        - CMD
        - wget
        - '--no-verbose'
        - '--spider'
        - 'http://localhost:7700/health'
      retries: 3
      timeout: 5s
      networks:
        - development

volumes:
  db-meilisearch:
    driver: local
networks:
  development:
    driver: bridge
