version: '3.1'

services:
  db-mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: development
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_mysql:/var/lib/mysql
    networks:
      - development

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db-mysql
      PMA_PORT: 3306
      PMA_USER: development
      PMA_PASSWORD: password
    depends_on:
      - db-mysql
    networks:
      - development

volumes:
  db_mysql:
    driver: local

networks:
  development:
    name: development
    driver: bridge
