version: '3.1'

services:
  db-redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'db-redis:/data'
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s
      networks:
        - development

volumes:
  db-redis:
    driver: local
networks:
  development:
    driver: bridge
